---
- hosts: all
  gather_facts: False
  tasks:
  - name: install python 3
    raw: test -e /usr/bin/python3 -a -e /usr/bin/pip3 || (apt-get -y update && apt-get install -y python3-minimal python3-setuptools python3-pip)
    tags:
    - [ never, initial-setup ]

- hosts: all
  roles:
  - role: common
    tags: [ initial-setup ]
  - role: user
    tags: [ initial-setup ]
  - dev-sec.ssh-hardening
  - oefenweb.fail2ban
  - disable-swap
  - setup-loadbalancer
  - role: install-kubeadm
    tags: [ install-kubeadm ]
  - role: bootstrap-nodes
    tags: [ never, bootstrap-nodes ]
