---
# - name: Install ufw
#   apt:
#     name: ufw
#     state: present
#     update_cache: yes

- name: Deny everything incoming
  community.general.ufw:
    policy: "deny"
    direction: "incoming"

- name: Allow outgoing traffic
  community.general.ufw:
    policy: "allow"
    direction: "outgoing"

- name: Set ssh to "limit"
  community.general.ufw:
    rule: limit
    port: "22"
    proto: tcp
    direction: in

- name: Allow communication with other hosts through private ips
  community.general.ufw:
    rule: allow
    src: "{{ hostvars[item].private_ip }}"
    proto: any
  loop: "{{ groups['all'] | flatten(levels=1) }}"

- name: "Allow incoming traffic to port {{ vip_kube_apiserver_port }} to address {{ keepalived_vip }}"
  community.general.ufw:
    rule: allow
    port: "{{ vip_kube_apiserver_port }}"
    proto: tcp
    to_ip: "{{ keepalived_vip }}"
    direction: "in"

- name: "Allow some ports 80 and 443"
  community.general.ufw:
    rule: allow
    port: "{{ vip_kube_apiserver_port }}"
    proto: tcp
    to_ip: "{{ keepalived_vip }}"
    direction: "in"
  loop: "{{ ['80', '443'] | flatten(levels=1) }}"
